// <auto-generated />
using DictionatiesForEverything.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DictionatiesForEverything.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251127124037_UpdateStructureDatabase")]
    partial class UpdateStructureDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DictionatiesForEverything.Model.Glossary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Glossaries");
                });

            modelBuilder.Entity("DictionatiesForEverything.Model.GlossaryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GlossaryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GlossaryItems");
                });

            modelBuilder.Entity("DictionatiesForEverything.Model.GlossaryItemImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int?>("GlossaryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItmeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GlossaryItemId");

                    b.ToTable("GlossaryItemImages");
                });

            modelBuilder.Entity("DictionatiesForEverything.Model.GlossaryItemImages", b =>
                {
                    b.HasOne("DictionatiesForEverything.Model.GlossaryItem", null)
                        .WithMany("Images")
                        .HasForeignKey("GlossaryItemId");
                });

            modelBuilder.Entity("DictionatiesForEverything.Model.GlossaryItem", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
